[envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
[envs.default.scripts]
cov = [
  "test-cov",
  "cov-report",
]
cov-report = [
  "- coverage combine",
  "coverage html",
]
serve = "uvicorn metafunction:app --reload"
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"

[envs.lint]
detached = true
dependencies = [
  "black>=22.10.0",
  "mypy>=0.991",
  "pydantic",
  "ruff>=0.0.166",
  "sqlmodel",
]
[envs.lint.scripts]
fix = [
  "black {args:.}",
  "ruff check --fix {args:.}",
  "style",
]
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
types = "mypy --install-types --non-interactive {args:src/metafunction tests}"
all = [
  "style",
  "types",
]
